spring.application.name=Task Master

# PORT
server.port=3005

# System configuration
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
management.endpoint.health.show-details=always

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmaster
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=Zaid@123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update